all :










./obj/ScoreSystem.o : ./src/ScoreSystem.cpp ./src/ScoreSystem.h
			g++ -Wall -c ./src/ScoreSystem.cpp -o ./obj/ScoreSystem.o



./obj/Projectile.o : ./src/Projectile.cpp ./src/Projectile.h
			g++ -Wall -c ./src/Projectile.cpp -o ./obj/Projectile.o 



./obj/Position.o : ./src/Position.cpp ./src/Position.h
			g++ -Wall -c ./src/Position.cpp -o ./obj/Position.o


./obj/Playership.o : ./src/Playership.cpp ./src/Playership.h
			g++ -g -Wall -c ./src/Playership.cpp -o ./obj/Playership.o


./obj/Invaders.o : ./src/Invaders.cpp ./src/Invaders.h 
			g++ -g -Wall -c ./src/Invaders.cpp -o ./obj/Invaders.o